name: Push code to Lambda
on:
        push:
                branches:
                        - main
                paths:
                        - "backend/**"

permissions:
        id-token: write
        contents: read

jobs:
        update-lambda:
                runs-on: ubuntu-latest
                steps:
                        - name: Checkout code
                          uses: actions/checkout@v3

                        - name: Install Go
                          uses: actions/setup-go@v6
                          with:
                                  go-version: "1.25"
                                  go-version-file: "./backend/go.mod"
                                  token: ${{ github.token }}
                                  cache-dependency-path: "./backend/go.sum"

                        - name: Install dependencies
                          run: cd backend && go mod download

                        - name: Build the Go binary
                          run: cd backend/cmd && GOOS=linux GOARCH=arm64 go build -tags lambda.norpc -o bootstrap main.go

                        - name: Zip the Lambda
                          run: cd backend/cmd && zip doclane-backend.zip bootstrap

                        - name: Configure AWS credentials
                          uses: aws-actions/configure-aws-credentials@v4
                          with:
                                  role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
                                  aws-region: ${{ secrets.AWS_REGION }}

                        - name: Update Lambda code
                          run: |
                                  cd backend/cmd && \
                                  aws lambda update-function-code \
                                    --function-name DoclaneBackend \
                                    --zip-file fileb://doclane-backend.zip \
                                    --query 'FunctionArn' \
                                    --output text
